User creation
julialuciani/CustomerAPI pull request #1
Opened 2022-11-21 13:48 UTC by julialuciani

- CRUD
- Validação que impede de adicionar customer com cpf e email iguais
- Quando customer não existe é retornado NotFound
- Validação de confirmação email
- Validação de cpf e save sem caracteres especiais
- Retornos de endoint coerentes com o card

Link do card: https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-1049

2022-11-21 15:18 UTC, viniciusoliveira-warren commented on CustomerAPI/Controllers/CustomerController.cs
> +            }
```suggestion
                return Ok();
            } 
```

2022-11-21 15:18 UTC, viniciusoliveira-warren commented on CustomerAPI/Controllers/CustomerController.cs
> +
```suggestion
}

```

2022-11-21 15:19 UTC, viniciusoliveira-warren commented on CustomerAPI/Controllers/CustomerController.cs
> +
Só limpando linhas em branco no final do arquivo ☝

2022-11-21 15:24 UTC, viniciusoliveira-warren commented on Data/Utilities/FormatStrings.cs
> +        {
Ajustar indentação ctrl K + D

2022-11-21 15:25 UTC, viniciusoliveira-warren commented on Data/Interface/ICustomerService.cs
> +    }
Interface já é publica, redundante explicitar nos métodos também
```suggestion
        void Create(Customer customer);
        IEnumerable<Customer> GetAll();
        Customer GetById(long id);
        void Update(Customer customer);
        void Delete(long id);
    }
```

2022-11-21 15:26 UTC, viniciusoliveira-warren commented on Data/Entities/Customer.cs
> +}
Além da linha em branco também ajustar indentação ctrl K + D
```suggestion
    }
}
```

2022-11-21 17:06 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +            RuleFor(customer => customer.FullName)
```suggestion
        {
            RuleFor(customer => customer.FullName)
```

2022-11-21 17:08 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +                .NotEmpty().WithMessage("Name cannot remain empty")
Validações próprias do FluentValidation não precisa sobrescrever suas mensagem pois são bem descritivas
```suggestion
                .NotEmpty()
```

2022-11-21 17:08 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +                .EmailAddress().WithMessage("Email is not valId");
Validações próprias do FluentValidation não precisa sobrescrever suas mensagem pois são bem descritivas
```suggestion
                .NotEmpty()
                .EmailAddress().WithMessage("Email is not valId");
```

2022-11-21 17:08 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +                .Equal(customer => customer.Email).WithMessage("Email confirmation is different than Email");
Validações próprias do FluentValidation não precisa sobrescrever suas mensagem pois são bem descritivas
```suggestion
                .NotEmpty()
                .Equal(customer => customer.Email).WithMessage("Email confirmation is different than Email");
```

2022-11-21 17:11 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +                .Must(CpfValIdation);
Validações próprias do FluentValidation não precisa sobrescrever suas mensagem pois são bem descritivas
```suggestion
                .NotEmpty()
                .Must(CpfValIdation).WithMessage("'Cpf' did not match the expected format: 00000000000");
```

2022-11-21 17:11 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +                .NotEmpty().WithMessage("Cellphone cannot remain empty");
Validações próprias do FluentValidation não precisa sobrescrever suas mensagem pois são bem descritivas
```suggestion
                .NotEmpty();
```

2022-11-21 17:12 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +                .Must(VerifyAge).WithMessage("Customer cannot be registered if he is a minor");
Validações próprias do FluentValidation não precisa sobrescrever suas mensagem pois são bem descritivas
```suggestion
                .NotEmpty()
                .Must(VerifyAge).WithMessage("'Customer' must be legal age.");
```

2022-11-21 17:13 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +                .NotEmpty().WithMessage("Country cannot remain empty");
Validações próprias do FluentValidation não precisa sobrescrever suas mensagem pois são bem descritivas. PS: Mesmo comentários para os casos abaixo
```suggestion
                .NotEmpty();
```

2022-11-21 17:16 UTC, viniciusoliveira-warren commented on Data/Entities/Customer.cs
> +        public long Id { get; set; }
```suggestion
            Number = number;
        }
        
        public long Id { get; set; }
```

2022-11-21 17:17 UTC, viniciusoliveira-warren commented on Data/Services/CustomerService.cs
> +            if (checkingCustomerCpf != null || checkingCustomerEmail != null) throw new ArgumentNullException("Customer already exists");
1. Estourar uma exceção especifica para cada validação para que fique claro para o usuário qual o erro
2. Utilizar método Any ao invés do FirstOrDefault quando apenas precisar verificar se existe para ganho de performance

2022-11-21 17:18 UTC, viniciusoliveira-warren commented on Data/Services/CustomerService.cs
> +            if (customer != null) return customer;
Utilizar método Any ao invés do FirstOrDefault quando apenas precisar verificar se existe para ganho de performance

2022-11-21 17:20 UTC, viniciusoliveira-warren commented on Data/Services/CustomerService.cs
> +            throw new ArgumentException("Customer doesn't exist!");
Não existe para o que? Devemos sempre especificar o problema com detalhes para que seja possível entender o erro
```suggestion
            throw new ArgumentException($"Customer does not exist for Id: {id}.");
```

2022-11-21 17:21 UTC, ghost commented on Data/Services/CustomerService.cs
> +            int customerIndex = _customerList.FindIndex(element => element.Id == customer.Id);
Não está sendo utilizado
```suggestion
            int customerIndex = _customerList.FindIndex(element => element.Id == customer.Id);
```

2022-11-21 17:21 UTC, viniciusoliveira-warren commented on Data/Services/CustomerService.cs
> +            if (customerIndex == -1) throw new ArgumentNullException("Customer not found with Id: " + customer.Id);
```suggestion
            if (customerIndex == -1) throw new ArgumentNullException($"Customer not found for Id: {customer.Id}");
```

2022-11-21 17:24 UTC, viniciusoliveira-warren commented on Data/Services/CustomerService.cs
> +            if (customerId < 0) throw new ArgumentNullException("Customer not found with Id: " + Id);
```suggestion
            var exists = _customerList.Any(x => x.Id == Id);
            if (!exists) throw new ArgumentNullException($"Customer not found for Id: {id}");
```

2022-11-21 17:26 UTC, viniciusoliveira-warren commented on Data/Services/CustomerService.cs
> +                throw new ArgumentException("Customer can't have Email equal to other customer!");
```suggestion
                throw new ArgumentException($"Customer for Email: {customer.Email} already exists!");
```

2022-11-21 17:26 UTC, viniciusoliveira-warren commented on Data/Services/CustomerService.cs
> +                throw new ArgumentException("Customer can't have Cpf equal to other customer!");
```suggestion
                throw new ArgumentException($"Customer for Email: {customer.Cpf} already exists!");
```

2022-11-21 17:28 UTC, viniciusoliveira-warren commented on Data/Services/CustomerService.cs
> +        public virtual void Create(Customer customer)
Por que os métodos estão como Virtual? métodos virtuais podem ser sobrescrevidos por quem for utilizar a classe e isso não será necessário

2022-11-21 17:29 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +                string tempCpf;
Se começou o código em inglês deve manter o padrão em todo o projeto
```suggestion
            private static bool IsCpfValid(string Cpf)
            {
                int[] multiplicador1 = new int[9] { 10, 9, 8, 7, 6, 5, 4, 3, 2 };
                int[] multiplicador2 = new int[10] { 11, 10, 9, 8, 7, 6, 5, 4, 3, 2 };
                string tempCpf;
```

2022-11-21 17:51 UTC, gregoryzimmerwarren requested changes
Deixei alguns comentários e sugestões.

Qualquer dúvida estou a disposição.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Controllers/CustomerController.cs
> +using System;
Da uma verificada, não apenas nestes usings, mas em todos os teus, se por acaso não tem nenhum que está ali sem ser utilizado. O atalho pra isso é Ctrl + R +G (precisa fazer em cada arquivo separadamente).

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Controllers/CustomerController.cs
> +                return Created("Created", customer);
```suggestion
                _service.Create(customer);
                return Created("Id: ", customer.Id);
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Controllers/CustomerController.cs
> +                return Created("Created", customer);
Aqui é interessante informar ao usuário como resposta, o Id dele, e não a entidade completa. Se não, ele precisaria utilizar o GetAll para descobrir isso primeiro antes de poder utilizar dos outros métodos.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Controllers/CustomerController.cs
> +                return BadRequest(exception.Message);
Como tu tá trazendo um ArgumentNullException teu return deveria ser um NotFound(). Mas na verdade o correto é ser um BadRequest() mesmo como tu fez, então tens que utilizar o ArgumentException. Da uma verificada no teu método para alterar também. O ArgumentNullException vai ser quando tu fizer uma busca no banco e não encontrar nada.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Controllers/CustomerController.cs
> +            return Ok(listCustomers);
Coloca num try catch também, com o catch sem parâmetro retornando um NoContent()

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Controllers/CustomerController.cs
> +                return Ok();
```suggestion
                return NoContent();
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Controllers/CustomerController.cs
> +                return Ok();
O Ok(), que é a resposta 200 é mais utilizada para Get, que é quando a gente quer dizer que deu certo e  a gente traz algo para apresentar para o usuário. Quando a gente faz um Delete utilizamos o NoContent() que é a resposta 204, que também diz que deu tudo certo na solicitação, mas não traz nada.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Program.cs
>  // Add services to the container.
```suggestion
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Program.cs
>  // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
```suggestion
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Program.cs
Não estou conseguindo selecionar a linha 21, mas pode apagar também, é só comentário.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Program.cs
> +
```suggestion
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +
Eu vi que o @viniciusoliveira-warren já comentou nas tuas validações, então vou passar.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +                Cpf = Cpf.Replace(".", "").Replace("-", "");
Você criou Strings Extensions, sendo uma delas a FormatingCpf(). Você pode utilizar aqui para não ter que ficar refazendo esse trabalho.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +                    return false;
```suggestion

                if (Cpf.Length != 11)
                    return false;
                    
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +                    return false;
Além dessa verificação você também precisa ver se o CPF é formado apenas pelo menos número, 111.111.111-11 por exemplo, porque este também não é um formato válido, e que vai passar na tua validação da forma que está no momento.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +        }
```suggestion
            }
        }
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +            }
```suggestion
                for (int i = 0; i < 9; i++)
                    soma += int.Parse(tempCpf[i].ToString()) * multiplicador1[i];
                    
                resto = soma % 11;
                
                if (resto < 2)
                    resto = 0;
                else
                    resto = 11 - resto;
                    
                digito = resto.ToString();
                tempCpf = tempCpf + digito;
                soma = 0;
                
                for (int i = 0; i < 10; i++)
                    soma += int.Parse(tempCpf[i].ToString()) * multiplicador2[i];
                    
                resto = soma % 11;
                
                if (resto < 2)
                    resto = 0;
                else
                    resto = 11 - resto;
                    
                digito = digito + resto.ToString();
                
                return Cpf.EndsWith(digito);
            }
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +            }
Muitas linhas em branco as vezes são desnecessárias, mas penso que as vezes é bom separar um pouco o que tá acontecendo nos métodos para ficar melhor de visualizar.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Data.csproj
> +    <Nullable>enable</Nullable>
```suggestion
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Data.csproj
> +    <Nullable>enable</Nullable>
Retirando isso tu vais ter que fazer todas as importações e nulidades manualmente. Da uma verificada em todos os teus arquivos dentro da pasta Data.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Data.csproj
> +    <Nullable>enable</Nullable>
Eu não consigo fazer lá, mas faz a mesma coisa no CustomerAPI.csproj e também da uma olhada nos teus arquivos daquela pasta.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +            static bool VerifyAge(System.DateTime dateOfBirth)
```suggestion
            private static bool IsOver18(System.DateTime dateOfBirth)
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +            static bool CpfValIdation(string Cpf)
```suggestion
            private static bool IsValidCpf(string Cpf)
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Entities/Customer.cs
> +
```suggestion
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Entities/Customer.cs
> +         )
```suggestion
            int number)
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +        private List<Customer> _customerList = new List<Customer>();
```suggestion
        private List<Customer> _customerList = new();
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +        private List<Customer> _customerList = new List<Customer>();
O AspNet permite que você não precise tipar novamente tua variável após o new.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +        private List<Customer> _customerList = new List<Customer>();
Eu vi que o @viniciusoliveira-warren deixou comentários nesse arquivo, então vou passar por ele, porque pelo que eu vi não acredito que contribuiria com algo a mais, além do fato de te recomendar separar um pouco as coisas dentro dos métodos para facilitar a leitura.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Utilities/FormatStrings.cs
> +            return Postalcode.Trim().Replace(".", "").Replace("-", "");
```suggestion
            return Postalcode.Trim().Replace(".", "").Replace("-", "").Replace(",", "").Replace(" ", "");
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Utilities/FormatStrings.cs
> +            return Postalcode.Trim().Replace(".", "").Replace("-", "");
Por garantia eu acredito ser sempre bom tentar evitar qualquer possível forma que o usuário possa querer digitar.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Utilities/FormatStrings.cs
> +            return Cellphone.Trim().Replace("(", "").Replace(")", "").Replace("-", "").Replace(" ", "");
```suggestion
            return Cellphone.Trim().Replace("(", "").Replace(")", "").Replace("-", "").Replace(" ", "").Replace(".", "").Replace(",", "");
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Utilities/FormatStrings.cs
> +            return Cellphone.Trim().Replace("(", "").Replace(")", "").Replace("-", "").Replace(" ", "");
Mesmo caso anterior.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Utilities/FormatStrings.cs
> +            return Cpf.Trim().Replace(".", "").Replace("-", "");
```suggestion
            return Cpf.Trim().Replace(".", "").Replace("-", "").Replace(",", "").Replace(" ", "");
```

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Utilities/FormatStrings.cs
> +            return Cpf.Trim().Replace(".", "").Replace("-", "");
Mesmo caso anterior.

2022-11-21 17:51 UTC, gregoryzimmerwarren commented on Data/Utilities/FormatStrings.cs
> +    }
```suggestion
        }
    }
```

2022-11-21 17:53 UTC, viniciusoliveira-warren commented on Data/Utilities/FormatStrings.cs
> +            return Cpf.Trim().Replace(".", "").Replace("-", "");
O .Trim já faz `.Replace(" ", "")`, em que cenário seria necessário esse replace?

2022-11-21 17:56 UTC, ghost commented on CustomerAPI/Controllers/CustomerController.cs
> +                return Ok();
Não necessariamente, o propósito do comentário está certo mas a explicação nem tanto
![image](https://user-images.githubusercontent.com/96585621/203126543-3ffa42dd-9896-40ca-9476-c80e8c33296b.png)

2022-11-21 17:56 UTC, viniciusoliveira-warren commented on CustomerAPI/Controllers/CustomerController.cs
> +                return Ok();
200 está apenas dizendo que o request foi um sucesso, não diz que precisa retornar algum dado

2022-11-21 17:56 UTC, viniciusoliveira-warren commented on CustomerAPI/Controllers/CustomerController.cs
> +                return Ok();
![image](https://user-images.githubusercontent.com/96585621/203126670-1cda357b-ec13-4949-a465-c9bfe0dbf01a.png)

2022-11-21 17:57 UTC, gregoryzimmerwarren commented on Data/Utilities/FormatStrings.cs
> +            return Cpf.Trim().Replace(".", "").Replace("-", "");
Numa possibilidade de alguém escrever por exemplo, 111.111.111 11, ele iria conseguir remover esse espaço antes dos dois últimos dígitos?

2022-11-21 17:58 UTC, viniciusoliveira-warren commented on CustomerAPI/Controllers/CustomerController.cs
> +                return Ok();
A razão de retornar 204 é porque não tem retorno nenhum daquele endpoint

2022-11-21 18:02 UTC, viniciusoliveira-warren commented on Data/Utilities/FormatStrings.cs
> +            return Cpf.Trim().Replace(".", "").Replace("-", "");
Boa

2022-11-21 18:22 UTC, gregoryzimmerwarren requested changes
Deixei mais uns comentários.

2022-11-21 18:22 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +
```suggestion
            RuleFor(customer => customer.City)
                .NotEmpty();

            RuleFor(customer => customer.Postalcode)
                .NotEmpty();

            RuleFor(customer => customer.Address)
                .NotEmpty();

            RuleFor(customer => customer.Number)
                .NotEmpty();
```

2022-11-21 18:22 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +
Mesmo caso que o @viniciusoliveira-warren havia comentado, só não vi que ele tinha posto o PS no comentário dele 😅

2022-11-21 18:22 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +
```suggestion
```

2022-11-22 12:35 UTC, julialuciani commented on Data/Services/CustomerService.cs
> +            if (customer != null) return customer;
Bom dia, troquei todos os métodos que tinham o FirstOrDefault por Any, porém nesse caso não funciona já que ele precisa retornar um Customer quando Any retorna bool.

2022-11-22 12:38 UTC, julialuciani commented on CustomerAPI/Validators/CustomerValidator.cs
> +            static bool VerifyAge(System.DateTime dateOfBirth)
Bom dia, não consigo colocar private nesses métodos pois estou utilizando eles no construtor.

2022-11-22 12:38 UTC, julialuciani commented on CustomerAPI/Validators/CustomerValidator.cs
> +            static bool CpfValIdation(string Cpf)
Bom dia, não consigo colocar private nesses métodos pois estou utilizando eles no construtor.

2022-11-22 13:30 UTC, gregoryzimmerwarren requested changes
Fiz novos comentários, qualquer coisa estou a disposição.

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on CustomerAPI/Controllers/CustomerController.cs
> +        }
```suggestion
            }
        }
```

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on CustomerAPI/Program.cs
> +
```suggestion
```

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +                    return false;
Antes você precisa fazer a formatação utilizando teu .FormatingCpf(), caso contrário sempre vai ser falso.

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on Data/Entities/Customer.cs
> +            long id,
```suggestion
```

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on Data/Entities/Customer.cs
> +            Id = id;
```suggestion
```

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on Data/Entities/Customer.cs
> +            long id,
Não precisa passar no teu construtor, porque não é o usuário que vai se atribuir um Id, e sim teu método Create.

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +
```suggestion
}
```

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +            if (checkingCustomerEmail == true) throw new ArgumentException($"Customer for Email: {customer.Email} already exists!");
```suggestion
            if (_customerList.Any(customerElement => customerElement.Cpf == customer.Cpf))
               throw new ArgumentException($"Customer for Cpf: {customer.Cpf} already exists!");
            
            if (_customerList.Any(customerElement => customerElement.Email == customer.Email))
               throw new ArgumentException($"Customer for Email: {customer.Email} already exists!");
```

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +            customer.Id = _customerList.Count + 1;
Essa tua forma de determinar o Id não vai dar certo.

Veja só, se você tiver uma lista com 5 usuários (1, 2, 3, 4 e 5) e você adicionar mais um usuário, vai dar certo, vais ter 6 (1, 2, 3, 4, 5 e 6), tudo ok.
Mas voltando para os 5 usuários, se você deletar, por exemplo, o número 2, vais ter 4 usuários (1, 3, 4 e 5). Após isso você resolve adicionar outro. De acordo com a tua lógica, como tem 4 usuários, o Id no novo é 4 + 1 = 5, ou seja, tu teria dois usuários com Id repetidos (1, 3, 4, 5 e 5), o que não estaria certo.

Te recomendo usar a extension de List chamada LastOrDefault(), que procura o último elemento que queremos, ou atribui um padrão. Assim podemos usar: 
.LastOrDefault()?.Id + 1 ?? 1;
que vai procurar o último Id. Se ele existir vai pegar esse Id e somar 1, se não existir o Id será 1.

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +        {
```suggestion
        }
        
        public void Update(Customer customer)
        {
```

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +        public void Delete(long Id)
```suggestion
            _customerList[customerIndex] = customer;
        }
        
        public void Delete(long Id)
```

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on Data/Utilities/FormatStrings.cs
> +        public static string FormatingCellphone(this string Cellphone)
```suggestion
        }
        
        public static string FormatingCellphone(this string Cellphone)
```

2022-11-22 13:30 UTC, gregoryzimmerwarren commented on Data/Utilities/FormatStrings.cs
> +        public static string FormatingCpf(this string Cpf)
```suggestion
        }
        
        public static string FormatingCpf(this string Cpf)
```

2022-11-22 13:48 UTC, julialuciani commented on CustomerAPI/Validators/CustomerValidator.cs
> +                    return false;
Verdade Greg, é um ponto interessante, não tinha pensado nisso

2022-11-22 13:54 UTC, julialuciani commented on Data/Services/CustomerService.cs
> +            customer.Id = _customerList.Count + 1;
Entendi, realmente não tinha refletido sobre

2022-11-22 15:06 UTC, gregoryzimmerwarren requested changes
Deixei mais alguns comentários.

2022-11-22 15:06 UTC, gregoryzimmerwarren commented on CustomerAPI/Validators/CustomerValidator.cs
> +namespace Data.Validators
```suggestion
using System.Runtime.CompilerServices;

namespace Data.Validators
```

2022-11-22 15:06 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +            int customerIndex = _customerList.FindIndex(element => element.Id == customer.Id);
```suggestion
        {
            int customerIndex = _customerList.FindIndex(element => element.Id == customer.Id);
```

2022-11-22 15:06 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +        }
```suggestion
            _customerList[customerIndex] = customer;
        }
```

2022-11-22 15:06 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +            _customerList.RemoveAll(element => element.Id == Id);
Aqui se você quiser, poderia chamar o GetById e dai usar o .Remove passando o customer que ele trouxer, porque caso de erro o Get já vai lançar a exception.

2022-11-22 15:28 UTC, julialuciani commented on Data/Services/CustomerService.cs
> +            _customerList.RemoveAll(element => element.Id == Id);
boa

2022-11-22 16:07 UTC, gregoryzimmerwarren approved these changes
Deixei mais um comentário. Mas acredito que da minha parte seja isso. Vou deixar aprovado.

2022-11-22 16:07 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +            if (checkingCustomerCpf == true) throw new ArgumentException($"Customer for Cpf: {customer.Cpf} already exists!");
```suggestion
            var checkingCustomerCpf = _customerList.Any(customerElement => customerElement.Cpf == customer.Cpf);
            
            var checkingCustomerEmail = _customerList.Any(customerElement => customerElement.Email == customer.Email);
            
            if (checkingCustomerCpf == true) throw new ArgumentException($"Customer for Cpf: {customer.Cpf} already exists!");
```

2022-11-22 16:30 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +            static bool IsCpfValid(string cpf)
```suggestion
            private static bool IsCpfValid(string cpf)
```

2022-11-22 16:31 UTC, ghost commented on CustomerAPI/Validators/CustomerValidator.cs
> +            static bool IsOver18(System.DateTime dateOfBirth)
```suggestion
            private static bool AgeRequirementIsMeet(DateTime dateOfBirth)
```

2022-11-22 16:36 UTC, DevClaudinei commented on Data/Services/CustomerService.cs
> +            customer.Id = _customerList.LastOrDefault()?.Id + 1 ?? 1;
Eu sugiro que você retorne esse id para a controller e este seja mostrado.

2022-11-22 16:37 UTC, santosclaudinei-warren commented on CustomerAPI/Controllers/CustomerController.cs
> +                _service.Create(customer);
receber o id da customer service como retorno e mostrar na linha abaixo.

2022-11-22 16:37 UTC, julialuciani commented on CustomerAPI/Validators/CustomerValidator.cs
> +            static bool IsOver18(System.DateTime dateOfBirth)
Alterei o nome, porém não consigo alterar para privado por algum motivo
<img width="535" alt="image" src="https://user-images.githubusercontent.com/113135536/203370557-96f17cdb-f1f5-4f41-8838-8c7bffdb1a09.png">

2022-11-22 16:39 UTC, julialuciani commented on CustomerAPI/Validators/CustomerValidator.cs
> +            static bool IsCpfValid(string cpf)
Não consigo alterar para privado por algum motivo 
<img width="574" alt="image" src="https://user-images.githubusercontent.com/113135536/203370798-7deb8d8f-0642-4f75-91f6-3a91339b02fe.png">

2022-11-22 16:41 UTC, viniciusoliveira-warren commented on Data/Services/CustomerService.cs
> +            if (checkingCustomerEmail == true) throw new ArgumentException($"Customer for Email: {customer.Email} already exists!");
1. Se uma validação dar erro podemos estourar exceção e parar o fluxo ai mesmo, não devemos esperar as 2 validações terminarem 
2. Não precisa validar se um boolean é `true ou false`, basta fazer `if (seuBool)` para verificar true e `if (!seuBool)` para verificar false
CC: @gregoryzimmerwarren 

```suggestion
            var cpfAlreadyExists = _customerList.Any(customerElement => customerElement.Cpf == customer.Cpf);
            if (cpfAlreadyExists) throw new ArgumentException($"Customer for Cpf: {customer.Cpf} already exists!");
            
            var emailAlreadyExists = _customerList.Any(customerElement => customerElement.Email == customer.Email);
            if (emailAlreadyExists) throw new ArgumentException($"Customer for Email: {customer.Email} already exists!");
```

2022-11-22 16:42 UTC, ghost commented on Data/Services/CustomerService.cs
> +            return _customerList;
Essa exceção não faz sentido, se a lista não tem valores então é simplesmente uma lista vazia que neste momento não tem dados. CC: @gregoryzimmerwarren 
```suggestion
            return _customerList;
```

2022-11-22 16:43 UTC, viniciusoliveira-warren commented on Data/Services/CustomerService.cs
> +            throw new ArgumentException($"Customer not found for Id: {Id}");
Mesma coisa mas de uma forma mais fácil de entender
```suggestion
            var customer = _customerList.FirstOrDefault(customer => customer.Id == Id)
                ?? throw new ArgumentException($"Customer not found for Id: {Id}");
            
            return customer;
```

2022-11-22 16:48 UTC, viniciusoliveira-warren commented on CustomerAPI/Controllers/CustomerController.cs
> +            }
Apenas devemos retornar 204 quando o endpoint não possui retorno o que nunca vai ser o caso aqui, como estamos fazendo GetAll ou vai retornar os dados ou uma lista vazia quando não tiver nenhum dado, ou seja, possui retorno. CC: @gregoryzimmerwarren 
```suggestion
            try
            {
                var listCustomers = _service.GetAll();
                return Ok(listCustomers);
            }
            catch (Exception ex)
            {
                var exMessage = ex.InnerException?.Message ?? ex.Message;
                return Problem(exMessage);
            }
```

2022-11-22 16:48 UTC, julialuciani commented on Data/Services/CustomerService.cs
> +            throw new ArgumentException($"Customer not found for Id: {Id}");
boaa

2022-11-22 16:49 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +            static bool IsOver18(System.DateTime dateOfBirth)
Qual o erro?

2022-11-22 16:49 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +            static bool IsCpfValid(string cpf)
Qual o erro?

2022-11-22 17:28 UTC, viniciusoliveira-warren commented on CustomerAPI/Validators/CustomerValidator.cs
> +            int[] mult1 = new int[9] { 10, 9, 8, 7, 6, 5, 4, 3, 2 };
```suggestion
            RuleFor(customer => customer.Number)
                .NotEmpty();    
       }
       
       public static bool IsCpfValid(string cpf)
       {
            int[] mult1 = new int[9] { 10, 9, 8, 7, 6, 5, 4, 3, 2 };
```

2022-11-22 17:29 UTC, viniciusoliveira-warren commented on CustomerAPI/Controllers/CustomerController.cs
> +            }
Está estourando exceção mas em momento algum faz uso dela
![image](https://user-images.githubusercontent.com/96585621/203381629-0fb0e80f-5125-4188-9746-c8c5daf9bfae.png)
```suggestion
            catch (ArgumentException ex)
            {
                return NotFound(ex.Message);
            }
```

2022-11-22 19:04 UTC, viniciusoliveira-warren approved these changes

2022-11-22 19:04 UTC, merged